apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: '{{ default (randAlphaNum 24) .Values.POSTGRES_PASSWORD | b64enc | quote }}'
  RABBITMQ_DEFAULT_PASS: '{{ default (randAlphaNum 128) .Values.RABBITMQ_DEFAULT_PASS | b64enc | quote }}'
  RABBITMQ_ERLANG_COOKIE: '{{ default (randAlphaNum 128) .Values.RABBITMQ_ERLANG_COOKIE | b64enc | quote }}'
  TAIGA_SECRET: '{{ default (randAlphaNum 128) .Values.TAIGA_SECRET | b64enc | quote }}'
  EMAIL_HOST_PASSWORD: '{{ default (randAlphaNum 128) .Values.EMAIL_HOST_PASSWORD | b64enc | quote }}'
